In [66]:
import numpy as np

X = np.array([[0,1,1],[1,1,6],[2,1,1],[3,1,2]])
X_input = np.array([[0,1,2],[1,1,1],[2,2,2]])

In [24]:

np.abs(X - X_input)

array([[0, 0, 1],
       [1, 0, 1],
       [2, 0, 1],
       [3, 0, 0]])

In [29]:
for input in X_input:
    print(np.sum(np.abs(X - input), axis=1))

[1 2 3 3]
[1 0 1 3]
[4 3 2 2]


In [67]:
container = np.empty((X_input.shape[0], X.shape[0]))
for index, input in enumerate(X_input):
    container[index] = np.linalg.norm(X - input, axis=1)

In [71]:
index_container = np.argsort(container, axis=1)[:,:2]
distance_container = np.sort(container, axis=1)[:,:2]

In [92]:
y = np.array([[1,1,3,4],[2,2,3,10]])

In [81]:
for data in zip(index_container,distance_container):
    print(data[1], np.sum(data[1]))

[1.         2.23606798] 3.23606797749979
[1. 1.] 2.0
[1.41421356 1.41421356] 2.8284271247461903


In [25]:
(1.1 == 0).astype(int)

AttributeError: 'bool' object has no attribute 'astype'

In [64]:
import numpy as np
y = np.array([0, 0, 1, 2])
index = np.array([[1,2,0],[2,3,2]])

In [65]:
y_target = y[index]
y_target

array([[0, 1, 0],
       [1, 2, 1]])

In [66]:
np.unique(y_target)

array([0, 1, 2])

In [ ]:
[[2,1],[0,3]]

In [78]:
container = np.ones((len(np.unique(y_target)), y_target.shape[0]))
for index, i in enumerate(np.unique(y_target)):
    container[index] = np.count_nonzero(y_target == i, axis=1)
container = container.T

In [90]:
container/np.sum(container, axis=1).reshape(-1,1)

array([[0.66666667, 0.33333333, 0.        ],
       [0.        , 0.66666667, 0.33333333]])

In [96]:
np.sum((np.array([[1,1,1],[2,2,2]]) * np.array([[2,4,2],[3,3,3]])), axis=1) / np.array([2,2])

array([4., 9.])

In [85]:
np.divide(container, np.sum(container, axis=1))

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [52]:
for y in y_target:
    print(np.unique(y, return_counts=True)[1]/np.sum(np.unique(y, return_counts=True)[1]))

[0.66666667 0.33333333]
[1.]


In [17]:
a1 = np.array([3,0])
a2 = np.array([0,4])

np.linalg.norm(a2-a1)

5.0

In [42]:
a = np.array([[1, 0, 0], [1, 0, 7], [2, 3, 4]])
np.unique(a, axis=0)

array([[1, 0, 0],
       [1, 0, 7],
       [2, 3, 4]])