In [66]:
import numpy as np

X = np.array([[0,1,1],[1,1,6],[2,1,1],[3,1,2]])
X_input = np.array([[0,1,2],[1,1,1],[2,2,2]])

In [24]:

np.abs(X - X_input)

array([[0, 0, 1],
       [1, 0, 1],
       [2, 0, 1],
       [3, 0, 0]])

In [29]:
for input in X_input:
    print(np.sum(np.abs(X - input), axis=1))

[1 2 3 3]
[1 0 1 3]
[4 3 2 2]


In [67]:
container = np.empty((X_input.shape[0], X.shape[0]))
for index, input in enumerate(X_input):
    container[index] = np.linalg.norm(X - input, axis=1)

In [71]:
index_container = np.argsort(container, axis=1)[:,:2]
distance_container = np.sort(container, axis=1)[:,:2]

In [92]:
y = np.array([[1,1,3,4],[2,2,3,10]])

In [81]:
for data in zip(index_container,distance_container):
    print(data[1], np.sum(data[1]))

[1.         2.23606798] 3.23606797749979
[1. 1.] 2.0
[1.41421356 1.41421356] 2.8284271247461903


In [94]:
np.argmax(y,axis=1)

array([3, 3])

In [58]:
y[[1,5]]

array([0, 3])

In [47]:
np.argsort(container, axis=1)[:,:2]

array([[0, 1],
       [1, 0],
       [2, 3]])

In [17]:
a1 = np.array([3,0])
a2 = np.array([0,4])

np.linalg.norm(a2-a1)

5.0

In [14]:
def compute_distance(self,
                        x_1 : np.array,
                        x_2 : np.array) -> np.array :
    """Compute distance between data input and registered data

    Args:
        x1 (np.array) (m,1): Input data array
        x2 (np.array) (m,1): Registered data array

    Returns:
        np.array (scalar): Distance of x1 and x2 
    """
    abs_diff = np.abs(x_1-x_2)
    sigma_diff = np.sum(np.power(abs_diff, self.power))
    dist = np.power(sigma_diff, 1.0/self.power)

    return dist